broker: "127.0.0.1:6379"
result_backend: "127.0.0.1:6379"

redis:
  max_idle: 12
  max_active: 123
  max_idle_timeout: 456
  wait: true
  read_timeout: 17
  write_timeout: 19
  connect_timeout: 21
  normal_tasks_poll_period: 1001
  delayed_tasks_poll_period: 23
  delayed_tasks_key: kratos
