// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: comm/enum.proto

package comm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyType int32

const (
	VerifyType_None      VerifyType = 0
	VerifyType_Login     VerifyType = 1
	VerifyType_Register  VerifyType = 2
	VerifyType_SetPwd    VerifyType = 3
	VerifyType_SetEmail  VerifyType = 4
	VerifyType_SetMobile VerifyType = 5
)

// Enum value maps for VerifyType.
var (
	VerifyType_name = map[int32]string{
		0: "None",
		1: "Login",
		2: "Register",
		3: "SetPwd",
		4: "SetEmail",
		5: "SetMobile",
	}
	VerifyType_value = map[string]int32{
		"None":      0,
		"Login":     1,
		"Register":  2,
		"SetPwd":    3,
		"SetEmail":  4,
		"SetMobile": 5,
	}
)

func (x VerifyType) Enum() *VerifyType {
	p := new(VerifyType)
	*p = x
	return p
}

func (x VerifyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerifyType) Descriptor() protoreflect.EnumDescriptor {
	return file_comm_enum_proto_enumTypes[0].Descriptor()
}

func (VerifyType) Type() protoreflect.EnumType {
	return &file_comm_enum_proto_enumTypes[0]
}

func (x VerifyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerifyType.Descriptor instead.
func (VerifyType) EnumDescriptor() ([]byte, []int) {
	return file_comm_enum_proto_rawDescGZIP(), []int{0}
}

type ThirdPlatformCode int32

const (
	ThirdPlatformCode_pf_None ThirdPlatformCode = 0
	// pf_Email = 1;
	// pf_Mobile = 2;
	ThirdPlatformCode_pf_IM     ThirdPlatformCode = 3 //IM
	ThirdPlatformCode_pf_QL     ThirdPlatformCode = 4
	ThirdPlatformCode_pf_Halala ThirdPlatformCode = 5
)

// Enum value maps for ThirdPlatformCode.
var (
	ThirdPlatformCode_name = map[int32]string{
		0: "pf_None",
		3: "pf_IM",
		4: "pf_QL",
		5: "pf_Halala",
	}
	ThirdPlatformCode_value = map[string]int32{
		"pf_None":   0,
		"pf_IM":     3,
		"pf_QL":     4,
		"pf_Halala": 5,
	}
)

func (x ThirdPlatformCode) Enum() *ThirdPlatformCode {
	p := new(ThirdPlatformCode)
	*p = x
	return p
}

func (x ThirdPlatformCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThirdPlatformCode) Descriptor() protoreflect.EnumDescriptor {
	return file_comm_enum_proto_enumTypes[1].Descriptor()
}

func (ThirdPlatformCode) Type() protoreflect.EnumType {
	return &file_comm_enum_proto_enumTypes[1]
}

func (x ThirdPlatformCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThirdPlatformCode.Descriptor instead.
func (ThirdPlatformCode) EnumDescriptor() ([]byte, []int) {
	return file_comm_enum_proto_rawDescGZIP(), []int{1}
}

type CanalEvent int32

const (
	CanalEvent_ce_none             CanalEvent = 0
	CanalEvent_ce_SpaceWorkItem    CanalEvent = 1
	CanalEvent_ce_SpaceWorkObject  CanalEvent = 5
	CanalEvent_ce_SpaceMember      CanalEvent = 3
	CanalEvent_ce_SpaceTag         CanalEvent = 4
	CanalEvent_ce_Space            CanalEvent = 6
	CanalEvent_ce_User             CanalEvent = 2
	CanalEvent_ce_SpaceWorkVersion CanalEvent = 7
)

// Enum value maps for CanalEvent.
var (
	CanalEvent_name = map[int32]string{
		0: "ce_none",
		1: "ce_SpaceWorkItem",
		5: "ce_SpaceWorkObject",
		3: "ce_SpaceMember",
		4: "ce_SpaceTag",
		6: "ce_Space",
		2: "ce_User",
		7: "ce_SpaceWorkVersion",
	}
	CanalEvent_value = map[string]int32{
		"ce_none":             0,
		"ce_SpaceWorkItem":    1,
		"ce_SpaceWorkObject":  5,
		"ce_SpaceMember":      3,
		"ce_SpaceTag":         4,
		"ce_Space":            6,
		"ce_User":             2,
		"ce_SpaceWorkVersion": 7,
	}
)

func (x CanalEvent) Enum() *CanalEvent {
	p := new(CanalEvent)
	*p = x
	return p
}

func (x CanalEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CanalEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_comm_enum_proto_enumTypes[2].Descriptor()
}

func (CanalEvent) Type() protoreflect.EnumType {
	return &file_comm_enum_proto_enumTypes[2]
}

func (x CanalEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CanalEvent.Descriptor instead.
func (CanalEvent) EnumDescriptor() ([]byte, []int) {
	return file_comm_enum_proto_rawDescGZIP(), []int{2}
}

var File_comm_enum_proto protoreflect.FileDescriptor

var file_comm_enum_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x63, 0x6f, 0x6d, 0x6d, 0x2a, 0x58, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x50,
	0x77, 0x64, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x10,
	0x05, 0x2a, 0x45, 0x0a, 0x11, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x70, 0x66, 0x5f, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x70, 0x66, 0x5f, 0x49, 0x4d, 0x10, 0x03, 0x12, 0x09,
	0x0a, 0x05, 0x70, 0x66, 0x5f, 0x51, 0x4c, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x70, 0x66, 0x5f,
	0x48, 0x61, 0x6c, 0x61, 0x6c, 0x61, 0x10, 0x05, 0x2a, 0xa0, 0x01, 0x0a, 0x0a, 0x43, 0x61, 0x6e,
	0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x63, 0x65, 0x5f, 0x6e, 0x6f,
	0x6e, 0x65, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x63, 0x65, 0x5f, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x63, 0x65,
	0x5f, 0x53, 0x70, 0x61, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x63, 0x65, 0x5f, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x63, 0x65, 0x5f, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x54, 0x61, 0x67, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x63, 0x65, 0x5f, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x63, 0x65, 0x5f, 0x55, 0x73, 0x65, 0x72,
	0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x63, 0x65, 0x5f, 0x53, 0x70, 0x61, 0x63, 0x65, 0x57, 0x6f,
	0x72, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x10, 0x07, 0x42, 0x15, 0x5a, 0x13, 0x67,
	0x6f, 0x2d, 0x63, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x3b, 0x63, 0x6f,
	0x6d, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comm_enum_proto_rawDescOnce sync.Once
	file_comm_enum_proto_rawDescData = file_comm_enum_proto_rawDesc
)

func file_comm_enum_proto_rawDescGZIP() []byte {
	file_comm_enum_proto_rawDescOnce.Do(func() {
		file_comm_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_comm_enum_proto_rawDescData)
	})
	return file_comm_enum_proto_rawDescData
}

var file_comm_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_comm_enum_proto_goTypes = []interface{}{
	(VerifyType)(0),        // 0: comm.VerifyType
	(ThirdPlatformCode)(0), // 1: comm.ThirdPlatformCode
	(CanalEvent)(0),        // 2: comm.CanalEvent
}
var file_comm_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comm_enum_proto_init() }
func file_comm_enum_proto_init() {
	if File_comm_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comm_enum_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comm_enum_proto_goTypes,
		DependencyIndexes: file_comm_enum_proto_depIdxs,
		EnumInfos:         file_comm_enum_proto_enumTypes,
	}.Build()
	File_comm_enum_proto = out.File
	file_comm_enum_proto_rawDesc = nil
	file_comm_enum_proto_goTypes = nil
	file_comm_enum_proto_depIdxs = nil
}
