// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: space_tag/v1/space_tag.proto

package v1

import (
	comm "go-cs/api/comm"
	bean "go-cs/internal/bean"
	rsp "go-cs/internal/bean/vo/rsp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSpaceTagOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceId int64 `protobuf:"varint,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	FromIdx int64 `protobuf:"varint,2,opt,name=fromIdx,proto3" json:"fromIdx,omitempty"`
	ToIdx   int64 `protobuf:"varint,3,opt,name=toIdx,proto3" json:"toIdx,omitempty"`
}

func (x *SetSpaceTagOrderRequest) Reset() {
	*x = SetSpaceTagOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_tag_v1_space_tag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSpaceTagOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpaceTagOrderRequest) ProtoMessage() {}

func (x *SetSpaceTagOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_tag_v1_space_tag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpaceTagOrderRequest.ProtoReflect.Descriptor instead.
func (*SetSpaceTagOrderRequest) Descriptor() ([]byte, []int) {
	return file_space_tag_v1_space_tag_proto_rawDescGZIP(), []int{0}
}

func (x *SetSpaceTagOrderRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *SetSpaceTagOrderRequest) GetFromIdx() int64 {
	if x != nil {
		return x.FromIdx
	}
	return 0
}

func (x *SetSpaceTagOrderRequest) GetToIdx() int64 {
	if x != nil {
		return x.ToIdx
	}
	return 0
}

type SetSpaceTagOrderReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*SetSpaceTagOrderReply_Error
	Result isSetSpaceTagOrderReply_Result `protobuf_oneof:"result"`
}

func (x *SetSpaceTagOrderReply) Reset() {
	*x = SetSpaceTagOrderReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_tag_v1_space_tag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSpaceTagOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpaceTagOrderReply) ProtoMessage() {}

func (x *SetSpaceTagOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_space_tag_v1_space_tag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpaceTagOrderReply.ProtoReflect.Descriptor instead.
func (*SetSpaceTagOrderReply) Descriptor() ([]byte, []int) {
	return file_space_tag_v1_space_tag_proto_rawDescGZIP(), []int{1}
}

func (m *SetSpaceTagOrderReply) GetResult() isSetSpaceTagOrderReply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *SetSpaceTagOrderReply) GetError() *comm.ErrorInfo {
	if x, ok := x.GetResult().(*SetSpaceTagOrderReply_Error); ok {
		return x.Error
	}
	return nil
}

type isSetSpaceTagOrderReply_Result interface {
	isSetSpaceTagOrderReply_Result()
}

type SetSpaceTagOrderReply_Error struct {
	Error *comm.ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

func (*SetSpaceTagOrderReply_Error) isSetSpaceTagOrderReply_Result() {}

type CreateSpaceTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagName string `protobuf:"bytes,1,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	SpaceId int64  `protobuf:"zigzag64,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
}

func (x *CreateSpaceTagRequest) Reset() {
	*x = CreateSpaceTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_tag_v1_space_tag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpaceTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceTagRequest) ProtoMessage() {}

func (x *CreateSpaceTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_tag_v1_space_tag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceTagRequest.ProtoReflect.Descriptor instead.
func (*CreateSpaceTagRequest) Descriptor() ([]byte, []int) {
	return file_space_tag_v1_space_tag_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSpaceTagRequest) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *CreateSpaceTagRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

type CreateSpaceTagReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*CreateSpaceTagReply_Error
	//	*CreateSpaceTagReply_Data
	Result isCreateSpaceTagReply_Result `protobuf_oneof:"result"`
}

func (x *CreateSpaceTagReply) Reset() {
	*x = CreateSpaceTagReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_tag_v1_space_tag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpaceTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceTagReply) ProtoMessage() {}

func (x *CreateSpaceTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_space_tag_v1_space_tag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceTagReply.ProtoReflect.Descriptor instead.
func (*CreateSpaceTagReply) Descriptor() ([]byte, []int) {
	return file_space_tag_v1_space_tag_proto_rawDescGZIP(), []int{3}
}

func (m *CreateSpaceTagReply) GetResult() isCreateSpaceTagReply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *CreateSpaceTagReply) GetError() *comm.ErrorInfo {
	if x, ok := x.GetResult().(*CreateSpaceTagReply_Error); ok {
		return x.Error
	}
	return nil
}

func (x *CreateSpaceTagReply) GetData() *bean.SpaceTag {
	if x, ok := x.GetResult().(*CreateSpaceTagReply_Data); ok {
		return x.Data
	}
	return nil
}

type isCreateSpaceTagReply_Result interface {
	isCreateSpaceTagReply_Result()
}

type CreateSpaceTagReply_Error struct {
	Error *comm.ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type CreateSpaceTagReply_Data struct {
	Data *bean.SpaceTag `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*CreateSpaceTagReply_Error) isCreateSpaceTagReply_Result() {}

func (*CreateSpaceTagReply_Data) isCreateSpaceTagReply_Result() {}

type ModifySpaceTagNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagName string `protobuf:"bytes,1,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	SpaceId int64  `protobuf:"zigzag64,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	TagId   int64  `protobuf:"zigzag64,3,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *ModifySpaceTagNameRequest) Reset() {
	*x = ModifySpaceTagNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_tag_v1_space_tag_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifySpaceTagNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySpaceTagNameRequest) ProtoMessage() {}

func (x *ModifySpaceTagNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_tag_v1_space_tag_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySpaceTagNameRequest.ProtoReflect.Descriptor instead.
func (*ModifySpaceTagNameRequest) Descriptor() ([]byte, []int) {
	return file_space_tag_v1_space_tag_proto_rawDescGZIP(), []int{4}
}

func (x *ModifySpaceTagNameRequest) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *ModifySpaceTagNameRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *ModifySpaceTagNameRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type ModifySpaceTagNameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*ModifySpaceTagNameReply_Error
	//	*ModifySpaceTagNameReply_Data
	Result isModifySpaceTagNameReply_Result `protobuf_oneof:"result"`
}

func (x *ModifySpaceTagNameReply) Reset() {
	*x = ModifySpaceTagNameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_tag_v1_space_tag_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifySpaceTagNameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySpaceTagNameReply) ProtoMessage() {}

func (x *ModifySpaceTagNameReply) ProtoReflect() protoreflect.Message {
	mi := &file_space_tag_v1_space_tag_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySpaceTagNameReply.ProtoReflect.Descriptor instead.
func (*ModifySpaceTagNameReply) Descriptor() ([]byte, []int) {
	return file_space_tag_v1_space_tag_proto_rawDescGZIP(), []int{5}
}

func (m *ModifySpaceTagNameReply) GetResult() isModifySpaceTagNameReply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *ModifySpaceTagNameReply) GetError() *comm.ErrorInfo {
	if x, ok := x.GetResult().(*ModifySpaceTagNameReply_Error); ok {
		return x.Error
	}
	return nil
}

func (x *ModifySpaceTagNameReply) GetData() *bean.SpaceTag {
	if x, ok := x.GetResult().(*ModifySpaceTagNameReply_Data); ok {
		return x.Data
	}
	return nil
}

type isModifySpaceTagNameReply_Result interface {
	isModifySpaceTagNameReply_Result()
}

type ModifySpaceTagNameReply_Error struct {
	Error *comm.ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type ModifySpaceTagNameReply_Data struct {
	Data *bean.SpaceTag `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*ModifySpaceTagNameReply_Error) isModifySpaceTagNameReply_Result() {}

func (*ModifySpaceTagNameReply_Data) isModifySpaceTagNameReply_Result() {}

type DelSpaceTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceId int64 `protobuf:"zigzag64,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	TagId   int64 `protobuf:"zigzag64,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *DelSpaceTagRequest) Reset() {
	*x = DelSpaceTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_tag_v1_space_tag_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelSpaceTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSpaceTagRequest) ProtoMessage() {}

func (x *DelSpaceTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_tag_v1_space_tag_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSpaceTagRequest.ProtoReflect.Descriptor instead.
func (*DelSpaceTagRequest) Descriptor() ([]byte, []int) {
	return file_space_tag_v1_space_tag_proto_rawDescGZIP(), []int{6}
}

func (x *DelSpaceTagRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *DelSpaceTagRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type DelSpaceTagReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*DelSpaceTagReply_Error
	//	*DelSpaceTagReply_Data
	Result isDelSpaceTagReply_Result `protobuf_oneof:"result"`
}

func (x *DelSpaceTagReply) Reset() {
	*x = DelSpaceTagReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_tag_v1_space_tag_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelSpaceTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSpaceTagReply) ProtoMessage() {}

func (x *DelSpaceTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_space_tag_v1_space_tag_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSpaceTagReply.ProtoReflect.Descriptor instead.
func (*DelSpaceTagReply) Descriptor() ([]byte, []int) {
	return file_space_tag_v1_space_tag_proto_rawDescGZIP(), []int{7}
}

func (m *DelSpaceTagReply) GetResult() isDelSpaceTagReply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *DelSpaceTagReply) GetError() *comm.ErrorInfo {
	if x, ok := x.GetResult().(*DelSpaceTagReply_Error); ok {
		return x.Error
	}
	return nil
}

func (x *DelSpaceTagReply) GetData() *bean.SpaceTag {
	if x, ok := x.GetResult().(*DelSpaceTagReply_Data); ok {
		return x.Data
	}
	return nil
}

type isDelSpaceTagReply_Result interface {
	isDelSpaceTagReply_Result()
}

type DelSpaceTagReply_Error struct {
	Error *comm.ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type DelSpaceTagReply_Data struct {
	Data *bean.SpaceTag `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*DelSpaceTagReply_Error) isDelSpaceTagReply_Result() {}

func (*DelSpaceTagReply_Data) isDelSpaceTagReply_Result() {}

type GetSpaceTagListRequestV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceId int64 `protobuf:"zigzag64,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
}

func (x *GetSpaceTagListRequestV2) Reset() {
	*x = GetSpaceTagListRequestV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_tag_v1_space_tag_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceTagListRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceTagListRequestV2) ProtoMessage() {}

func (x *GetSpaceTagListRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_space_tag_v1_space_tag_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceTagListRequestV2.ProtoReflect.Descriptor instead.
func (*GetSpaceTagListRequestV2) Descriptor() ([]byte, []int) {
	return file_space_tag_v1_space_tag_proto_rawDescGZIP(), []int{8}
}

func (x *GetSpaceTagListRequestV2) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

type GetSpaceTagListReplyV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*GetSpaceTagListReplyV2_Error
	//	*GetSpaceTagListReplyV2_Data
	Result isGetSpaceTagListReplyV2_Result `protobuf_oneof:"result"`
}

func (x *GetSpaceTagListReplyV2) Reset() {
	*x = GetSpaceTagListReplyV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_tag_v1_space_tag_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceTagListReplyV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceTagListReplyV2) ProtoMessage() {}

func (x *GetSpaceTagListReplyV2) ProtoReflect() protoreflect.Message {
	mi := &file_space_tag_v1_space_tag_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceTagListReplyV2.ProtoReflect.Descriptor instead.
func (*GetSpaceTagListReplyV2) Descriptor() ([]byte, []int) {
	return file_space_tag_v1_space_tag_proto_rawDescGZIP(), []int{9}
}

func (m *GetSpaceTagListReplyV2) GetResult() isGetSpaceTagListReplyV2_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *GetSpaceTagListReplyV2) GetError() *comm.ErrorInfo {
	if x, ok := x.GetResult().(*GetSpaceTagListReplyV2_Error); ok {
		return x.Error
	}
	return nil
}

func (x *GetSpaceTagListReplyV2) GetData() *GetSpaceTagListReplyV2Data {
	if x, ok := x.GetResult().(*GetSpaceTagListReplyV2_Data); ok {
		return x.Data
	}
	return nil
}

type isGetSpaceTagListReplyV2_Result interface {
	isGetSpaceTagListReplyV2_Result()
}

type GetSpaceTagListReplyV2_Error struct {
	Error *comm.ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type GetSpaceTagListReplyV2_Data struct {
	Data *GetSpaceTagListReplyV2Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*GetSpaceTagListReplyV2_Error) isGetSpaceTagListReplyV2_Result() {}

func (*GetSpaceTagListReplyV2_Data) isGetSpaceTagListReplyV2_Result() {}

type GetSpaceTagListReplyV2Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*rsp.TagInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetSpaceTagListReplyV2Data) Reset() {
	*x = GetSpaceTagListReplyV2Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_tag_v1_space_tag_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceTagListReplyV2Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceTagListReplyV2Data) ProtoMessage() {}

func (x *GetSpaceTagListReplyV2Data) ProtoReflect() protoreflect.Message {
	mi := &file_space_tag_v1_space_tag_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceTagListReplyV2Data.ProtoReflect.Descriptor instead.
func (*GetSpaceTagListReplyV2Data) Descriptor() ([]byte, []int) {
	return file_space_tag_v1_space_tag_proto_rawDescGZIP(), []int{10}
}

func (x *GetSpaceTagListReplyV2Data) GetList() []*rsp.TagInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_space_tag_v1_space_tag_proto protoreflect.FileDescriptor

var file_space_tag_v1_space_tag_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x11, 0x63, 0x6f,
	0x6d, 0x6d, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x62,
	0x65, 0x61, 0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x15, 0x62, 0x65, 0x61, 0x6e, 0x2f, 0x76, 0x6f, 0x2f, 0x72, 0x73, 0x70, 0x2f, 0x74, 0x61, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x54, 0x61, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x66,
	0x72, 0x6f, 0x6d, 0x49, 0x64, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x72,
	0x6f, 0x6d, 0x49, 0x64, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x49, 0x64, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x49, 0x64, 0x78, 0x22, 0x4a, 0x0a, 0x15, 0x53,
	0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4d, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x12, 0x52, 0x07, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x7d, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x6f,
	0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x62, 0x65, 0x61, 0x6e, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x54, 0x61, 0x67, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x68, 0x0a, 0x19, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x12, 0x52,
	0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x12, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x22,
	0x81, 0x01, 0x0a, 0x17, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54,
	0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x6f, 0x5f, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x62, 0x65, 0x61, 0x6e, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61,
	0x67, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x46, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x12, 0x52, 0x07, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x12, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x22, 0x7a, 0x0a, 0x10, 0x44,
	0x65, 0x6c, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x27, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x67, 0x6f, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x62, 0x65, 0x61, 0x6e, 0x2e, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x54, 0x61, 0x67, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x08, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x35, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x56, 0x32, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x12, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x8b,
	0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x56, 0x32, 0x12, 0x27, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x3e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x56, 0x32, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3e, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x56, 0x32, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x73, 0x70, 0x2e, 0x54,
	0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0x90, 0x05, 0x0a,
	0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x12, 0x79, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x12, 0x23, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x3a, 0x01, 0x2a, 0x22,
	0x14, 0x2f, 0x6d, 0x79, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x74, 0x61, 0x67, 0x2f, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x8a, 0x01, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x54, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x24, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x1e, 0x3a, 0x01, 0x2a, 0x22, 0x19, 0x2f, 0x6d, 0x79, 0x2f, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x2f, 0x74, 0x61, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x2f, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x6d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61,
	0x67, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x3a, 0x01, 0x2a, 0x22, 0x11,
	0x2f, 0x6d, 0x79, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x74, 0x61, 0x67, 0x2f, 0x64, 0x65,
	0x6c, 0x12, 0x83, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x32, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54,
	0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x32, 0x1a,
	0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x56, 0x32, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x3a, 0x01, 0x2a,
	0x22, 0x15, 0x2f, 0x76, 0x32, 0x2f, 0x6d, 0x79, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x74,
	0x61, 0x67, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x85, 0x01, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x25, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x61, 0x67, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f,
	0x3a, 0x01, 0x2a, 0x22, 0x1a, 0x2f, 0x76, 0x32, 0x2f, 0x6d, 0x79, 0x2f, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x2f, 0x74, 0x61, 0x67, 0x2f, 0x73, 0x65, 0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x2f, 0x0a, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x74, 0x61, 0x67,
	0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x19, 0x67, 0x6f, 0x2d, 0x63, 0x73, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_space_tag_v1_space_tag_proto_rawDescOnce sync.Once
	file_space_tag_v1_space_tag_proto_rawDescData = file_space_tag_v1_space_tag_proto_rawDesc
)

func file_space_tag_v1_space_tag_proto_rawDescGZIP() []byte {
	file_space_tag_v1_space_tag_proto_rawDescOnce.Do(func() {
		file_space_tag_v1_space_tag_proto_rawDescData = protoimpl.X.CompressGZIP(file_space_tag_v1_space_tag_proto_rawDescData)
	})
	return file_space_tag_v1_space_tag_proto_rawDescData
}

var file_space_tag_v1_space_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_space_tag_v1_space_tag_proto_goTypes = []interface{}{
	(*SetSpaceTagOrderRequest)(nil),    // 0: api.space.v1.SetSpaceTagOrderRequest
	(*SetSpaceTagOrderReply)(nil),      // 1: api.space.v1.SetSpaceTagOrderReply
	(*CreateSpaceTagRequest)(nil),      // 2: api.space.v1.CreateSpaceTagRequest
	(*CreateSpaceTagReply)(nil),        // 3: api.space.v1.CreateSpaceTagReply
	(*ModifySpaceTagNameRequest)(nil),  // 4: api.space.v1.ModifySpaceTagNameRequest
	(*ModifySpaceTagNameReply)(nil),    // 5: api.space.v1.ModifySpaceTagNameReply
	(*DelSpaceTagRequest)(nil),         // 6: api.space.v1.DelSpaceTagRequest
	(*DelSpaceTagReply)(nil),           // 7: api.space.v1.DelSpaceTagReply
	(*GetSpaceTagListRequestV2)(nil),   // 8: api.space.v1.GetSpaceTagListRequestV2
	(*GetSpaceTagListReplyV2)(nil),     // 9: api.space.v1.GetSpaceTagListReplyV2
	(*GetSpaceTagListReplyV2Data)(nil), // 10: api.space.v1.GetSpaceTagListReplyV2Data
	(*comm.ErrorInfo)(nil),             // 11: comm.ErrorInfo
	(*bean.SpaceTag)(nil),              // 12: server_go_base.bean.SpaceTag
	(*rsp.TagInfo)(nil),                // 13: rsp.TagInfo
}
var file_space_tag_v1_space_tag_proto_depIdxs = []int32{
	11, // 0: api.space.v1.SetSpaceTagOrderReply.error:type_name -> comm.ErrorInfo
	11, // 1: api.space.v1.CreateSpaceTagReply.error:type_name -> comm.ErrorInfo
	12, // 2: api.space.v1.CreateSpaceTagReply.data:type_name -> server_go_base.bean.SpaceTag
	11, // 3: api.space.v1.ModifySpaceTagNameReply.error:type_name -> comm.ErrorInfo
	12, // 4: api.space.v1.ModifySpaceTagNameReply.data:type_name -> server_go_base.bean.SpaceTag
	11, // 5: api.space.v1.DelSpaceTagReply.error:type_name -> comm.ErrorInfo
	12, // 6: api.space.v1.DelSpaceTagReply.data:type_name -> server_go_base.bean.SpaceTag
	11, // 7: api.space.v1.GetSpaceTagListReplyV2.error:type_name -> comm.ErrorInfo
	10, // 8: api.space.v1.GetSpaceTagListReplyV2.data:type_name -> api.space.v1.GetSpaceTagListReplyV2Data
	13, // 9: api.space.v1.GetSpaceTagListReplyV2Data.list:type_name -> rsp.TagInfo
	2,  // 10: api.space.v1.space_tag.CreateSpaceTag:input_type -> api.space.v1.CreateSpaceTagRequest
	4,  // 11: api.space.v1.space_tag.ModifySpaceTagName:input_type -> api.space.v1.ModifySpaceTagNameRequest
	6,  // 12: api.space.v1.space_tag.DelSpaceTag:input_type -> api.space.v1.DelSpaceTagRequest
	8,  // 13: api.space.v1.space_tag.GetSpaceTagListV2:input_type -> api.space.v1.GetSpaceTagListRequestV2
	0,  // 14: api.space.v1.space_tag.SetSpaceTagOrder:input_type -> api.space.v1.SetSpaceTagOrderRequest
	3,  // 15: api.space.v1.space_tag.CreateSpaceTag:output_type -> api.space.v1.CreateSpaceTagReply
	5,  // 16: api.space.v1.space_tag.ModifySpaceTagName:output_type -> api.space.v1.ModifySpaceTagNameReply
	7,  // 17: api.space.v1.space_tag.DelSpaceTag:output_type -> api.space.v1.DelSpaceTagReply
	9,  // 18: api.space.v1.space_tag.GetSpaceTagListV2:output_type -> api.space.v1.GetSpaceTagListReplyV2
	1,  // 19: api.space.v1.space_tag.SetSpaceTagOrder:output_type -> api.space.v1.SetSpaceTagOrderReply
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_space_tag_v1_space_tag_proto_init() }
func file_space_tag_v1_space_tag_proto_init() {
	if File_space_tag_v1_space_tag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_space_tag_v1_space_tag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSpaceTagOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_tag_v1_space_tag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSpaceTagOrderReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_tag_v1_space_tag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpaceTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_tag_v1_space_tag_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpaceTagReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_tag_v1_space_tag_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifySpaceTagNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_tag_v1_space_tag_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifySpaceTagNameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_tag_v1_space_tag_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelSpaceTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_tag_v1_space_tag_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelSpaceTagReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_tag_v1_space_tag_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceTagListRequestV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_tag_v1_space_tag_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceTagListReplyV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_tag_v1_space_tag_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceTagListReplyV2Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_space_tag_v1_space_tag_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SetSpaceTagOrderReply_Error)(nil),
	}
	file_space_tag_v1_space_tag_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*CreateSpaceTagReply_Error)(nil),
		(*CreateSpaceTagReply_Data)(nil),
	}
	file_space_tag_v1_space_tag_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ModifySpaceTagNameReply_Error)(nil),
		(*ModifySpaceTagNameReply_Data)(nil),
	}
	file_space_tag_v1_space_tag_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*DelSpaceTagReply_Error)(nil),
		(*DelSpaceTagReply_Data)(nil),
	}
	file_space_tag_v1_space_tag_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*GetSpaceTagListReplyV2_Error)(nil),
		(*GetSpaceTagListReplyV2_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_space_tag_v1_space_tag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_space_tag_v1_space_tag_proto_goTypes,
		DependencyIndexes: file_space_tag_v1_space_tag_proto_depIdxs,
		MessageInfos:      file_space_tag_v1_space_tag_proto_msgTypes,
	}.Build()
	File_space_tag_v1_space_tag_proto = out.File
	file_space_tag_v1_space_tag_proto_rawDesc = nil
	file_space_tag_v1_space_tag_proto_goTypes = nil
	file_space_tag_v1_space_tag_proto_depIdxs = nil
}
