// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: work_item_role/v1/work_item_role.proto

package v1

import (
	comm "go-cs/api/comm"
	_ "go-cs/internal/bean"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取关联的任务数量
type GetTemplateRelationCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceId int64 `protobuf:"varint,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	Id      int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTemplateRelationCountRequest) Reset() {
	*x = GetTemplateRelationCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTemplateRelationCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRelationCountRequest) ProtoMessage() {}

func (x *GetTemplateRelationCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRelationCountRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRelationCountRequest) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{0}
}

func (x *GetTemplateRelationCountRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *GetTemplateRelationCountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTemplateRelationCountReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*GetTemplateRelationCountReply_Error
	//	*GetTemplateRelationCountReply_Data
	Result isGetTemplateRelationCountReply_Result `protobuf_oneof:"result"`
}

func (x *GetTemplateRelationCountReply) Reset() {
	*x = GetTemplateRelationCountReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTemplateRelationCountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRelationCountReply) ProtoMessage() {}

func (x *GetTemplateRelationCountReply) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRelationCountReply.ProtoReflect.Descriptor instead.
func (*GetTemplateRelationCountReply) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{1}
}

func (m *GetTemplateRelationCountReply) GetResult() isGetTemplateRelationCountReply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *GetTemplateRelationCountReply) GetError() *comm.ErrorInfo {
	if x, ok := x.GetResult().(*GetTemplateRelationCountReply_Error); ok {
		return x.Error
	}
	return nil
}

func (x *GetTemplateRelationCountReply) GetData() *GetTemplateRelationCountReplyData {
	if x, ok := x.GetResult().(*GetTemplateRelationCountReply_Data); ok {
		return x.Data
	}
	return nil
}

type isGetTemplateRelationCountReply_Result interface {
	isGetTemplateRelationCountReply_Result()
}

type GetTemplateRelationCountReply_Error struct {
	Error *comm.ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type GetTemplateRelationCountReply_Data struct {
	Data *GetTemplateRelationCountReplyData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*GetTemplateRelationCountReply_Error) isGetTemplateRelationCountReply_Result() {}

func (*GetTemplateRelationCountReply_Data) isGetTemplateRelationCountReply_Result() {}

type GetTemplateRelationCountReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetTemplateRelationCountReplyData) Reset() {
	*x = GetTemplateRelationCountReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTemplateRelationCountReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRelationCountReplyData) ProtoMessage() {}

func (x *GetTemplateRelationCountReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRelationCountReplyData.ProtoReflect.Descriptor instead.
func (*GetTemplateRelationCountReplyData) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{2}
}

func (x *GetTemplateRelationCountReplyData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取关联的任务数量
type GetWorkItemRelationCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceId int64 `protobuf:"varint,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	Id      int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetWorkItemRelationCountRequest) Reset() {
	*x = GetWorkItemRelationCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkItemRelationCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkItemRelationCountRequest) ProtoMessage() {}

func (x *GetWorkItemRelationCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkItemRelationCountRequest.ProtoReflect.Descriptor instead.
func (*GetWorkItemRelationCountRequest) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkItemRelationCountRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *GetWorkItemRelationCountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWorkItemRelationCountReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*GetWorkItemRelationCountReply_Error
	//	*GetWorkItemRelationCountReply_Data
	Result isGetWorkItemRelationCountReply_Result `protobuf_oneof:"result"`
}

func (x *GetWorkItemRelationCountReply) Reset() {
	*x = GetWorkItemRelationCountReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkItemRelationCountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkItemRelationCountReply) ProtoMessage() {}

func (x *GetWorkItemRelationCountReply) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkItemRelationCountReply.ProtoReflect.Descriptor instead.
func (*GetWorkItemRelationCountReply) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{4}
}

func (m *GetWorkItemRelationCountReply) GetResult() isGetWorkItemRelationCountReply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *GetWorkItemRelationCountReply) GetError() *comm.ErrorInfo {
	if x, ok := x.GetResult().(*GetWorkItemRelationCountReply_Error); ok {
		return x.Error
	}
	return nil
}

func (x *GetWorkItemRelationCountReply) GetData() *GetWorkItemRelationCountReplyData {
	if x, ok := x.GetResult().(*GetWorkItemRelationCountReply_Data); ok {
		return x.Data
	}
	return nil
}

type isGetWorkItemRelationCountReply_Result interface {
	isGetWorkItemRelationCountReply_Result()
}

type GetWorkItemRelationCountReply_Error struct {
	Error *comm.ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type GetWorkItemRelationCountReply_Data struct {
	Data *GetWorkItemRelationCountReplyData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*GetWorkItemRelationCountReply_Error) isGetWorkItemRelationCountReply_Result() {}

func (*GetWorkItemRelationCountReply_Data) isGetWorkItemRelationCountReply_Result() {}

type GetWorkItemRelationCountReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetWorkItemRelationCountReplyData) Reset() {
	*x = GetWorkItemRelationCountReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkItemRelationCountReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkItemRelationCountReplyData) ProtoMessage() {}

func (x *GetWorkItemRelationCountReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkItemRelationCountReplyData.ProtoReflect.Descriptor instead.
func (*GetWorkItemRelationCountReplyData) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkItemRelationCountReplyData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// -- 创建角色
type CreateSpaceWorkItemRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceId int64  `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// state_flow:状态流 | work_flow:节点流
	FlowScope string `protobuf:"bytes,3,opt,name=flow_scope,json=flowScope,proto3" json:"flow_scope,omitempty"`
}

func (x *CreateSpaceWorkItemRoleRequest) Reset() {
	*x = CreateSpaceWorkItemRoleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpaceWorkItemRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceWorkItemRoleRequest) ProtoMessage() {}

func (x *CreateSpaceWorkItemRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceWorkItemRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateSpaceWorkItemRoleRequest) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSpaceWorkItemRoleRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *CreateSpaceWorkItemRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSpaceWorkItemRoleRequest) GetFlowScope() string {
	if x != nil {
		return x.FlowScope
	}
	return ""
}

type CreateSpaceWorkItemRoleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*CreateSpaceWorkItemRoleReply_Error
	//	*CreateSpaceWorkItemRoleReply_Data
	Result isCreateSpaceWorkItemRoleReply_Result `protobuf_oneof:"result"`
}

func (x *CreateSpaceWorkItemRoleReply) Reset() {
	*x = CreateSpaceWorkItemRoleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpaceWorkItemRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceWorkItemRoleReply) ProtoMessage() {}

func (x *CreateSpaceWorkItemRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceWorkItemRoleReply.ProtoReflect.Descriptor instead.
func (*CreateSpaceWorkItemRoleReply) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{7}
}

func (m *CreateSpaceWorkItemRoleReply) GetResult() isCreateSpaceWorkItemRoleReply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *CreateSpaceWorkItemRoleReply) GetError() *comm.ErrorInfo {
	if x, ok := x.GetResult().(*CreateSpaceWorkItemRoleReply_Error); ok {
		return x.Error
	}
	return nil
}

func (x *CreateSpaceWorkItemRoleReply) GetData() string {
	if x, ok := x.GetResult().(*CreateSpaceWorkItemRoleReply_Data); ok {
		return x.Data
	}
	return ""
}

type isCreateSpaceWorkItemRoleReply_Result interface {
	isCreateSpaceWorkItemRoleReply_Result()
}

type CreateSpaceWorkItemRoleReply_Error struct {
	Error *comm.ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type CreateSpaceWorkItemRoleReply_Data struct {
	Data string `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*CreateSpaceWorkItemRoleReply_Error) isCreateSpaceWorkItemRoleReply_Result() {}

func (*CreateSpaceWorkItemRoleReply_Data) isCreateSpaceWorkItemRoleReply_Result() {}

// -- 删除角色
type DelSpaceWorkItemRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceId int64 `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Id      int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DelSpaceWorkItemRoleRequest) Reset() {
	*x = DelSpaceWorkItemRoleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelSpaceWorkItemRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSpaceWorkItemRoleRequest) ProtoMessage() {}

func (x *DelSpaceWorkItemRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSpaceWorkItemRoleRequest.ProtoReflect.Descriptor instead.
func (*DelSpaceWorkItemRoleRequest) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{8}
}

func (x *DelSpaceWorkItemRoleRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *DelSpaceWorkItemRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelSpaceWorkItemRoleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*DelSpaceWorkItemRoleReply_Error
	//	*DelSpaceWorkItemRoleReply_Data
	Result isDelSpaceWorkItemRoleReply_Result `protobuf_oneof:"result"`
}

func (x *DelSpaceWorkItemRoleReply) Reset() {
	*x = DelSpaceWorkItemRoleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelSpaceWorkItemRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSpaceWorkItemRoleReply) ProtoMessage() {}

func (x *DelSpaceWorkItemRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSpaceWorkItemRoleReply.ProtoReflect.Descriptor instead.
func (*DelSpaceWorkItemRoleReply) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{9}
}

func (m *DelSpaceWorkItemRoleReply) GetResult() isDelSpaceWorkItemRoleReply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *DelSpaceWorkItemRoleReply) GetError() *comm.ErrorInfo {
	if x, ok := x.GetResult().(*DelSpaceWorkItemRoleReply_Error); ok {
		return x.Error
	}
	return nil
}

func (x *DelSpaceWorkItemRoleReply) GetData() string {
	if x, ok := x.GetResult().(*DelSpaceWorkItemRoleReply_Data); ok {
		return x.Data
	}
	return ""
}

type isDelSpaceWorkItemRoleReply_Result interface {
	isDelSpaceWorkItemRoleReply_Result()
}

type DelSpaceWorkItemRoleReply_Error struct {
	Error *comm.ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type DelSpaceWorkItemRoleReply_Data struct {
	Data string `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*DelSpaceWorkItemRoleReply_Error) isDelSpaceWorkItemRoleReply_Result() {}

func (*DelSpaceWorkItemRoleReply_Data) isDelSpaceWorkItemRoleReply_Result() {}

// -- 修改名称
type SetSpaceWorkItemRoleNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceId int64  `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Id      int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SetSpaceWorkItemRoleNameRequest) Reset() {
	*x = SetSpaceWorkItemRoleNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSpaceWorkItemRoleNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpaceWorkItemRoleNameRequest) ProtoMessage() {}

func (x *SetSpaceWorkItemRoleNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpaceWorkItemRoleNameRequest.ProtoReflect.Descriptor instead.
func (*SetSpaceWorkItemRoleNameRequest) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{10}
}

func (x *SetSpaceWorkItemRoleNameRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *SetSpaceWorkItemRoleNameRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetSpaceWorkItemRoleNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetSpaceWorkItemRoleNameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*SetSpaceWorkItemRoleNameReply_Error
	//	*SetSpaceWorkItemRoleNameReply_Data
	Result isSetSpaceWorkItemRoleNameReply_Result `protobuf_oneof:"result"`
}

func (x *SetSpaceWorkItemRoleNameReply) Reset() {
	*x = SetSpaceWorkItemRoleNameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSpaceWorkItemRoleNameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpaceWorkItemRoleNameReply) ProtoMessage() {}

func (x *SetSpaceWorkItemRoleNameReply) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpaceWorkItemRoleNameReply.ProtoReflect.Descriptor instead.
func (*SetSpaceWorkItemRoleNameReply) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{11}
}

func (m *SetSpaceWorkItemRoleNameReply) GetResult() isSetSpaceWorkItemRoleNameReply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *SetSpaceWorkItemRoleNameReply) GetError() *comm.ErrorInfo {
	if x, ok := x.GetResult().(*SetSpaceWorkItemRoleNameReply_Error); ok {
		return x.Error
	}
	return nil
}

func (x *SetSpaceWorkItemRoleNameReply) GetData() string {
	if x, ok := x.GetResult().(*SetSpaceWorkItemRoleNameReply_Data); ok {
		return x.Data
	}
	return ""
}

type isSetSpaceWorkItemRoleNameReply_Result interface {
	isSetSpaceWorkItemRoleNameReply_Result()
}

type SetSpaceWorkItemRoleNameReply_Error struct {
	Error *comm.ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type SetSpaceWorkItemRoleNameReply_Data struct {
	Data string `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*SetSpaceWorkItemRoleNameReply_Error) isSetSpaceWorkItemRoleNameReply_Result() {}

func (*SetSpaceWorkItemRoleNameReply_Data) isSetSpaceWorkItemRoleNameReply_Result() {}

// ---设置排序
type SetSpaceWorkItemRoleRankingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceId   int64                                      `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	FlowScope string                                     `protobuf:"bytes,2,opt,name=flow_scope,json=flowScope,proto3" json:"flow_scope,omitempty"`
	List      []*SetSpaceWorkItemRoleRankingRequest_List `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SetSpaceWorkItemRoleRankingRequest) Reset() {
	*x = SetSpaceWorkItemRoleRankingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSpaceWorkItemRoleRankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpaceWorkItemRoleRankingRequest) ProtoMessage() {}

func (x *SetSpaceWorkItemRoleRankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpaceWorkItemRoleRankingRequest.ProtoReflect.Descriptor instead.
func (*SetSpaceWorkItemRoleRankingRequest) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{12}
}

func (x *SetSpaceWorkItemRoleRankingRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *SetSpaceWorkItemRoleRankingRequest) GetFlowScope() string {
	if x != nil {
		return x.FlowScope
	}
	return ""
}

func (x *SetSpaceWorkItemRoleRankingRequest) GetList() []*SetSpaceWorkItemRoleRankingRequest_List {
	if x != nil {
		return x.List
	}
	return nil
}

type SetSpaceWorkItemRoleRankingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*SetSpaceWorkItemRoleRankingReply_Error
	//	*SetSpaceWorkItemRoleRankingReply_Data
	Result isSetSpaceWorkItemRoleRankingReply_Result `protobuf_oneof:"result"`
}

func (x *SetSpaceWorkItemRoleRankingReply) Reset() {
	*x = SetSpaceWorkItemRoleRankingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSpaceWorkItemRoleRankingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpaceWorkItemRoleRankingReply) ProtoMessage() {}

func (x *SetSpaceWorkItemRoleRankingReply) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpaceWorkItemRoleRankingReply.ProtoReflect.Descriptor instead.
func (*SetSpaceWorkItemRoleRankingReply) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{13}
}

func (m *SetSpaceWorkItemRoleRankingReply) GetResult() isSetSpaceWorkItemRoleRankingReply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *SetSpaceWorkItemRoleRankingReply) GetError() *comm.ErrorInfo {
	if x, ok := x.GetResult().(*SetSpaceWorkItemRoleRankingReply_Error); ok {
		return x.Error
	}
	return nil
}

func (x *SetSpaceWorkItemRoleRankingReply) GetData() string {
	if x, ok := x.GetResult().(*SetSpaceWorkItemRoleRankingReply_Data); ok {
		return x.Data
	}
	return ""
}

type isSetSpaceWorkItemRoleRankingReply_Result interface {
	isSetSpaceWorkItemRoleRankingReply_Result()
}

type SetSpaceWorkItemRoleRankingReply_Error struct {
	Error *comm.ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type SetSpaceWorkItemRoleRankingReply_Data struct {
	Data string `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*SetSpaceWorkItemRoleRankingReply_Error) isSetSpaceWorkItemRoleRankingReply_Result() {}

func (*SetSpaceWorkItemRoleRankingReply_Data) isSetSpaceWorkItemRoleRankingReply_Result() {}

type SpaceRoleListQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceId int64 `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// state_flow:状态流 | work_flow:节点流
	FlowScope string `protobuf:"bytes,2,opt,name=flow_scope,json=flowScope,proto3" json:"flow_scope,omitempty"`
}

func (x *SpaceRoleListQueryRequest) Reset() {
	*x = SpaceRoleListQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceRoleListQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceRoleListQueryRequest) ProtoMessage() {}

func (x *SpaceRoleListQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceRoleListQueryRequest.ProtoReflect.Descriptor instead.
func (*SpaceRoleListQueryRequest) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{14}
}

func (x *SpaceRoleListQueryRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *SpaceRoleListQueryRequest) GetFlowScope() string {
	if x != nil {
		return x.FlowScope
	}
	return ""
}

type SpaceRoleListQueryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*SpaceRoleListQueryReply_Error
	//	*SpaceRoleListQueryReply_Data
	Result isSpaceRoleListQueryReply_Result `protobuf_oneof:"result"`
}

func (x *SpaceRoleListQueryReply) Reset() {
	*x = SpaceRoleListQueryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceRoleListQueryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceRoleListQueryReply) ProtoMessage() {}

func (x *SpaceRoleListQueryReply) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceRoleListQueryReply.ProtoReflect.Descriptor instead.
func (*SpaceRoleListQueryReply) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{15}
}

func (m *SpaceRoleListQueryReply) GetResult() isSpaceRoleListQueryReply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *SpaceRoleListQueryReply) GetError() *comm.ErrorInfo {
	if x, ok := x.GetResult().(*SpaceRoleListQueryReply_Error); ok {
		return x.Error
	}
	return nil
}

func (x *SpaceRoleListQueryReply) GetData() *SpaceRoleListQueryResult {
	if x, ok := x.GetResult().(*SpaceRoleListQueryReply_Data); ok {
		return x.Data
	}
	return nil
}

type isSpaceRoleListQueryReply_Result interface {
	isSpaceRoleListQueryReply_Result()
}

type SpaceRoleListQueryReply_Error struct {
	Error *comm.ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type SpaceRoleListQueryReply_Data struct {
	Data *SpaceRoleListQueryResult `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*SpaceRoleListQueryReply_Error) isSpaceRoleListQueryReply_Result() {}

func (*SpaceRoleListQueryReply_Data) isSpaceRoleListQueryReply_Result() {}

type SpaceRoleListQueryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*SpaceRoleListQueryResult_ListItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total int32                                `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *SpaceRoleListQueryResult) Reset() {
	*x = SpaceRoleListQueryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceRoleListQueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceRoleListQueryResult) ProtoMessage() {}

func (x *SpaceRoleListQueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceRoleListQueryResult.ProtoReflect.Descriptor instead.
func (*SpaceRoleListQueryResult) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{16}
}

func (x *SpaceRoleListQueryResult) GetList() []*SpaceRoleListQueryResult_ListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SpaceRoleListQueryResult) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SetSpaceWorkItemRoleRankingRequest_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Ranking int64 `protobuf:"varint,3,opt,name=ranking,proto3" json:"ranking,omitempty"`
}

func (x *SetSpaceWorkItemRoleRankingRequest_List) Reset() {
	*x = SetSpaceWorkItemRoleRankingRequest_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSpaceWorkItemRoleRankingRequest_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpaceWorkItemRoleRankingRequest_List) ProtoMessage() {}

func (x *SetSpaceWorkItemRoleRankingRequest_List) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpaceWorkItemRoleRankingRequest_List.ProtoReflect.Descriptor instead.
func (*SetSpaceWorkItemRoleRankingRequest_List) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{12, 0}
}

func (x *SetSpaceWorkItemRoleRankingRequest_List) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetSpaceWorkItemRoleRankingRequest_List) GetRanking() int64 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

type SpaceRoleListQueryResult_ListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid           string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SpaceId        uint64 `protobuf:"varint,3,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	WorkItemTypeId uint64 `protobuf:"varint,4,opt,name=work_item_type_id,json=workItemTypeId,proto3" json:"work_item_type_id,omitempty"`
	Key            string `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Name           string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Status         uint32 `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	IsSys          uint32 `protobuf:"varint,11,opt,name=is_sys,json=isSys,proto3" json:"is_sys,omitempty"`
	Ranking        uint64 `protobuf:"varint,8,opt,name=ranking,proto3" json:"ranking,omitempty"`
	CreatedAt      uint64 `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      uint64 `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FlowScope      string `protobuf:"bytes,12,opt,name=flow_scope,json=flowScope,proto3" json:"flow_scope,omitempty"`
}

func (x *SpaceRoleListQueryResult_ListItem) Reset() {
	*x = SpaceRoleListQueryResult_ListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceRoleListQueryResult_ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceRoleListQueryResult_ListItem) ProtoMessage() {}

func (x *SpaceRoleListQueryResult_ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_work_item_role_v1_work_item_role_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceRoleListQueryResult_ListItem.ProtoReflect.Descriptor instead.
func (*SpaceRoleListQueryResult_ListItem) Descriptor() ([]byte, []int) {
	return file_work_item_role_v1_work_item_role_proto_rawDescGZIP(), []int{16, 0}
}

func (x *SpaceRoleListQueryResult_ListItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpaceRoleListQueryResult_ListItem) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SpaceRoleListQueryResult_ListItem) GetSpaceId() uint64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *SpaceRoleListQueryResult_ListItem) GetWorkItemTypeId() uint64 {
	if x != nil {
		return x.WorkItemTypeId
	}
	return 0
}

func (x *SpaceRoleListQueryResult_ListItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SpaceRoleListQueryResult_ListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpaceRoleListQueryResult_ListItem) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SpaceRoleListQueryResult_ListItem) GetIsSys() uint32 {
	if x != nil {
		return x.IsSys
	}
	return 0
}

func (x *SpaceRoleListQueryResult_ListItem) GetRanking() uint64 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *SpaceRoleListQueryResult_ListItem) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SpaceRoleListQueryResult_ListItem) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *SpaceRoleListQueryResult_ListItem) GetFlowScope() string {
	if x != nil {
		return x.FlowScope
	}
	return ""
}

var File_work_item_role_v1_work_item_role_proto protoreflect.FileDescriptor

var file_work_item_role_v1_work_item_role_proto_rawDesc = []byte{
	0x0a, 0x26, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x1a,
	0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x10, 0x62, 0x65, 0x61, 0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0xa2, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x27, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4e, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x39, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22,
	0x4b, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa2, 0x01, 0x0a,
	0x1d, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x48,
	0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x39, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x6e, 0x0a, 0x1e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x66, 0x6c, 0x6f, 0x77, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x22, 0x67, 0x0a, 0x1c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x48, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x64, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x60, 0x0a, 0x1f, 0x53, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x68, 0x0a, 0x1d, 0x53, 0x65, 0x74, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0xe4, 0x01, 0x0a, 0x22, 0x53, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x57, 0x6f,
	0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x63, 0x6f, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6c, 0x6f, 0x77, 0x53, 0x63, 0x6f,
	0x70, 0x65, 0x12, 0x52, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x3e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x30, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x22, 0x6b, 0x0a, 0x20, 0x53, 0x65, 0x74, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x55, 0x0a, 0x19, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x6f,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x66, 0x6c, 0x6f, 0x77, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x22, 0x93, 0x01, 0x0a,
	0x17, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x45, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f,
	0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x6f, 0x6c,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0xc1, 0x03, 0x0a, 0x18, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x4c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x1a, 0xc0, 0x02, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x29, 0x0a, 0x11, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x73,
	0x79, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x73, 0x53, 0x79, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6c, 0x6f, 0x77, 0x5f,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6c, 0x6f,
	0x77, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x32, 0x98, 0x0a, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x9c, 0x01, 0x0a, 0x0e, 0x51, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x28, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x22, 0x3a, 0x01, 0x2a, 0x22, 0x1d, 0x2f, 0x6d, 0x79, 0x2f, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c,
	0x65, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0xc2, 0x01, 0x0a, 0x1b, 0x53, 0x65, 0x74, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x39, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x6f, 0x6c, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x37, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65,
	0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x61,
	0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2f, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x29, 0x3a, 0x01, 0x2a, 0x22, 0x24, 0x2f, 0x6d, 0x79, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2f,
	0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x73, 0x65, 0x74, 0x12, 0xb6, 0x01, 0x0a, 0x18,
	0x53, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x34, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26, 0x3a, 0x01,
	0x2a, 0x22, 0x21, 0x2f, 0x6d, 0x79, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x77, 0x6f, 0x72,
	0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2f, 0x6e, 0x61, 0x6d, 0x65,
	0x2f, 0x73, 0x65, 0x74, 0x12, 0xa5, 0x01, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x32, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x63, 0x65, 0x57, 0x6f,
	0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65,
	0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x3a, 0x01, 0x2a, 0x22, 0x1c,
	0x2f, 0x6d, 0x79, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69,
	0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2f, 0x64, 0x65, 0x6c, 0x12, 0xb1, 0x01, 0x0a,
	0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x35, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f,
	0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x24, 0x3a, 0x01, 0x2a, 0x22,
	0x1f, 0x2f, 0x6d, 0x79, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x5f,
	0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0xc6, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x36, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x57, 0x6f, 0x72, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x3c, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x36, 0x3a, 0x01, 0x2a, 0x22, 0x31, 0x2f, 0x6d, 0x79, 0x2f, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65,
	0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0xc5, 0x01, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x36, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72,
	0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x3b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x35, 0x3a, 0x01, 0x2a, 0x22,
	0x30, 0x2f, 0x6d, 0x79, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x5f,
	0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x42, 0x34, 0x0a, 0x15, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74,
	0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x19, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x6f, 0x6c,
	0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_work_item_role_v1_work_item_role_proto_rawDescOnce sync.Once
	file_work_item_role_v1_work_item_role_proto_rawDescData = file_work_item_role_v1_work_item_role_proto_rawDesc
)

func file_work_item_role_v1_work_item_role_proto_rawDescGZIP() []byte {
	file_work_item_role_v1_work_item_role_proto_rawDescOnce.Do(func() {
		file_work_item_role_v1_work_item_role_proto_rawDescData = protoimpl.X.CompressGZIP(file_work_item_role_v1_work_item_role_proto_rawDescData)
	})
	return file_work_item_role_v1_work_item_role_proto_rawDescData
}

var file_work_item_role_v1_work_item_role_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_work_item_role_v1_work_item_role_proto_goTypes = []interface{}{
	(*GetTemplateRelationCountRequest)(nil),         // 0: api.work_item_role.v1.GetTemplateRelationCountRequest
	(*GetTemplateRelationCountReply)(nil),           // 1: api.work_item_role.v1.GetTemplateRelationCountReply
	(*GetTemplateRelationCountReplyData)(nil),       // 2: api.work_item_role.v1.GetTemplateRelationCountReplyData
	(*GetWorkItemRelationCountRequest)(nil),         // 3: api.work_item_role.v1.GetWorkItemRelationCountRequest
	(*GetWorkItemRelationCountReply)(nil),           // 4: api.work_item_role.v1.GetWorkItemRelationCountReply
	(*GetWorkItemRelationCountReplyData)(nil),       // 5: api.work_item_role.v1.GetWorkItemRelationCountReplyData
	(*CreateSpaceWorkItemRoleRequest)(nil),          // 6: api.work_item_role.v1.CreateSpaceWorkItemRoleRequest
	(*CreateSpaceWorkItemRoleReply)(nil),            // 7: api.work_item_role.v1.CreateSpaceWorkItemRoleReply
	(*DelSpaceWorkItemRoleRequest)(nil),             // 8: api.work_item_role.v1.DelSpaceWorkItemRoleRequest
	(*DelSpaceWorkItemRoleReply)(nil),               // 9: api.work_item_role.v1.DelSpaceWorkItemRoleReply
	(*SetSpaceWorkItemRoleNameRequest)(nil),         // 10: api.work_item_role.v1.SetSpaceWorkItemRoleNameRequest
	(*SetSpaceWorkItemRoleNameReply)(nil),           // 11: api.work_item_role.v1.SetSpaceWorkItemRoleNameReply
	(*SetSpaceWorkItemRoleRankingRequest)(nil),      // 12: api.work_item_role.v1.SetSpaceWorkItemRoleRankingRequest
	(*SetSpaceWorkItemRoleRankingReply)(nil),        // 13: api.work_item_role.v1.SetSpaceWorkItemRoleRankingReply
	(*SpaceRoleListQueryRequest)(nil),               // 14: api.work_item_role.v1.SpaceRoleListQueryRequest
	(*SpaceRoleListQueryReply)(nil),                 // 15: api.work_item_role.v1.SpaceRoleListQueryReply
	(*SpaceRoleListQueryResult)(nil),                // 16: api.work_item_role.v1.SpaceRoleListQueryResult
	(*SetSpaceWorkItemRoleRankingRequest_List)(nil), // 17: api.work_item_role.v1.SetSpaceWorkItemRoleRankingRequest.List
	(*SpaceRoleListQueryResult_ListItem)(nil),       // 18: api.work_item_role.v1.SpaceRoleListQueryResult.ListItem
	(*comm.ErrorInfo)(nil),                          // 19: comm.ErrorInfo
}
var file_work_item_role_v1_work_item_role_proto_depIdxs = []int32{
	19, // 0: api.work_item_role.v1.GetTemplateRelationCountReply.error:type_name -> comm.ErrorInfo
	2,  // 1: api.work_item_role.v1.GetTemplateRelationCountReply.data:type_name -> api.work_item_role.v1.GetTemplateRelationCountReplyData
	19, // 2: api.work_item_role.v1.GetWorkItemRelationCountReply.error:type_name -> comm.ErrorInfo
	5,  // 3: api.work_item_role.v1.GetWorkItemRelationCountReply.data:type_name -> api.work_item_role.v1.GetWorkItemRelationCountReplyData
	19, // 4: api.work_item_role.v1.CreateSpaceWorkItemRoleReply.error:type_name -> comm.ErrorInfo
	19, // 5: api.work_item_role.v1.DelSpaceWorkItemRoleReply.error:type_name -> comm.ErrorInfo
	19, // 6: api.work_item_role.v1.SetSpaceWorkItemRoleNameReply.error:type_name -> comm.ErrorInfo
	17, // 7: api.work_item_role.v1.SetSpaceWorkItemRoleRankingRequest.list:type_name -> api.work_item_role.v1.SetSpaceWorkItemRoleRankingRequest.List
	19, // 8: api.work_item_role.v1.SetSpaceWorkItemRoleRankingReply.error:type_name -> comm.ErrorInfo
	19, // 9: api.work_item_role.v1.SpaceRoleListQueryReply.error:type_name -> comm.ErrorInfo
	16, // 10: api.work_item_role.v1.SpaceRoleListQueryReply.data:type_name -> api.work_item_role.v1.SpaceRoleListQueryResult
	18, // 11: api.work_item_role.v1.SpaceRoleListQueryResult.list:type_name -> api.work_item_role.v1.SpaceRoleListQueryResult.ListItem
	14, // 12: api.work_item_role.v1.WorkItemRole.QSpaceRoleList:input_type -> api.work_item_role.v1.SpaceRoleListQueryRequest
	12, // 13: api.work_item_role.v1.WorkItemRole.SetSpaceWorkItemRoleRanking:input_type -> api.work_item_role.v1.SetSpaceWorkItemRoleRankingRequest
	10, // 14: api.work_item_role.v1.WorkItemRole.SetSpaceWorkItemRoleName:input_type -> api.work_item_role.v1.SetSpaceWorkItemRoleNameRequest
	8,  // 15: api.work_item_role.v1.WorkItemRole.DelSpaceWorkItemRole:input_type -> api.work_item_role.v1.DelSpaceWorkItemRoleRequest
	6,  // 16: api.work_item_role.v1.WorkItemRole.CreateSpaceWorkItemRole:input_type -> api.work_item_role.v1.CreateSpaceWorkItemRoleRequest
	3,  // 17: api.work_item_role.v1.WorkItemRole.GetWorkItemRelationCount:input_type -> api.work_item_role.v1.GetWorkItemRelationCountRequest
	0,  // 18: api.work_item_role.v1.WorkItemRole.GetTemplateRelationCount:input_type -> api.work_item_role.v1.GetTemplateRelationCountRequest
	15, // 19: api.work_item_role.v1.WorkItemRole.QSpaceRoleList:output_type -> api.work_item_role.v1.SpaceRoleListQueryReply
	13, // 20: api.work_item_role.v1.WorkItemRole.SetSpaceWorkItemRoleRanking:output_type -> api.work_item_role.v1.SetSpaceWorkItemRoleRankingReply
	11, // 21: api.work_item_role.v1.WorkItemRole.SetSpaceWorkItemRoleName:output_type -> api.work_item_role.v1.SetSpaceWorkItemRoleNameReply
	9,  // 22: api.work_item_role.v1.WorkItemRole.DelSpaceWorkItemRole:output_type -> api.work_item_role.v1.DelSpaceWorkItemRoleReply
	7,  // 23: api.work_item_role.v1.WorkItemRole.CreateSpaceWorkItemRole:output_type -> api.work_item_role.v1.CreateSpaceWorkItemRoleReply
	4,  // 24: api.work_item_role.v1.WorkItemRole.GetWorkItemRelationCount:output_type -> api.work_item_role.v1.GetWorkItemRelationCountReply
	1,  // 25: api.work_item_role.v1.WorkItemRole.GetTemplateRelationCount:output_type -> api.work_item_role.v1.GetTemplateRelationCountReply
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_work_item_role_v1_work_item_role_proto_init() }
func file_work_item_role_v1_work_item_role_proto_init() {
	if File_work_item_role_v1_work_item_role_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_work_item_role_v1_work_item_role_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTemplateRelationCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTemplateRelationCountReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTemplateRelationCountReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkItemRelationCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkItemRelationCountReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkItemRelationCountReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpaceWorkItemRoleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpaceWorkItemRoleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelSpaceWorkItemRoleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelSpaceWorkItemRoleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSpaceWorkItemRoleNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSpaceWorkItemRoleNameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSpaceWorkItemRoleRankingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSpaceWorkItemRoleRankingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceRoleListQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceRoleListQueryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceRoleListQueryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSpaceWorkItemRoleRankingRequest_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_work_item_role_v1_work_item_role_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceRoleListQueryResult_ListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_work_item_role_v1_work_item_role_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GetTemplateRelationCountReply_Error)(nil),
		(*GetTemplateRelationCountReply_Data)(nil),
	}
	file_work_item_role_v1_work_item_role_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*GetWorkItemRelationCountReply_Error)(nil),
		(*GetWorkItemRelationCountReply_Data)(nil),
	}
	file_work_item_role_v1_work_item_role_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*CreateSpaceWorkItemRoleReply_Error)(nil),
		(*CreateSpaceWorkItemRoleReply_Data)(nil),
	}
	file_work_item_role_v1_work_item_role_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*DelSpaceWorkItemRoleReply_Error)(nil),
		(*DelSpaceWorkItemRoleReply_Data)(nil),
	}
	file_work_item_role_v1_work_item_role_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*SetSpaceWorkItemRoleNameReply_Error)(nil),
		(*SetSpaceWorkItemRoleNameReply_Data)(nil),
	}
	file_work_item_role_v1_work_item_role_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*SetSpaceWorkItemRoleRankingReply_Error)(nil),
		(*SetSpaceWorkItemRoleRankingReply_Data)(nil),
	}
	file_work_item_role_v1_work_item_role_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*SpaceRoleListQueryReply_Error)(nil),
		(*SpaceRoleListQueryReply_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_work_item_role_v1_work_item_role_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_work_item_role_v1_work_item_role_proto_goTypes,
		DependencyIndexes: file_work_item_role_v1_work_item_role_proto_depIdxs,
		MessageInfos:      file_work_item_role_v1_work_item_role_proto_msgTypes,
	}.Build()
	File_work_item_role_v1_work_item_role_proto = out.File
	file_work_item_role_v1_work_item_role_proto_rawDesc = nil
	file_work_item_role_v1_work_item_role_proto_goTypes = nil
	file_work_item_role_v1_work_item_role_proto_depIdxs = nil
}
