// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: work_item_role/v1/work_item_role.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WorkItemRole_QSpaceRoleList_FullMethodName              = "/api.work_item_role.v1.WorkItemRole/QSpaceRoleList"
	WorkItemRole_SetSpaceWorkItemRoleRanking_FullMethodName = "/api.work_item_role.v1.WorkItemRole/SetSpaceWorkItemRoleRanking"
	WorkItemRole_SetSpaceWorkItemRoleName_FullMethodName    = "/api.work_item_role.v1.WorkItemRole/SetSpaceWorkItemRoleName"
	WorkItemRole_DelSpaceWorkItemRole_FullMethodName        = "/api.work_item_role.v1.WorkItemRole/DelSpaceWorkItemRole"
	WorkItemRole_CreateSpaceWorkItemRole_FullMethodName     = "/api.work_item_role.v1.WorkItemRole/CreateSpaceWorkItemRole"
	WorkItemRole_GetWorkItemRelationCount_FullMethodName    = "/api.work_item_role.v1.WorkItemRole/GetWorkItemRelationCount"
	WorkItemRole_GetTemplateRelationCount_FullMethodName    = "/api.work_item_role.v1.WorkItemRole/GetTemplateRelationCount"
)

// WorkItemRoleClient is the client API for WorkItemRole service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkItemRoleClient interface {
	QSpaceRoleList(ctx context.Context, in *SpaceRoleListQueryRequest, opts ...grpc.CallOption) (*SpaceRoleListQueryReply, error)
	SetSpaceWorkItemRoleRanking(ctx context.Context, in *SetSpaceWorkItemRoleRankingRequest, opts ...grpc.CallOption) (*SetSpaceWorkItemRoleRankingReply, error)
	SetSpaceWorkItemRoleName(ctx context.Context, in *SetSpaceWorkItemRoleNameRequest, opts ...grpc.CallOption) (*SetSpaceWorkItemRoleNameReply, error)
	DelSpaceWorkItemRole(ctx context.Context, in *DelSpaceWorkItemRoleRequest, opts ...grpc.CallOption) (*DelSpaceWorkItemRoleReply, error)
	CreateSpaceWorkItemRole(ctx context.Context, in *CreateSpaceWorkItemRoleRequest, opts ...grpc.CallOption) (*CreateSpaceWorkItemRoleReply, error)
	GetWorkItemRelationCount(ctx context.Context, in *GetWorkItemRelationCountRequest, opts ...grpc.CallOption) (*GetWorkItemRelationCountReply, error)
	GetTemplateRelationCount(ctx context.Context, in *GetTemplateRelationCountRequest, opts ...grpc.CallOption) (*GetTemplateRelationCountReply, error)
}

type workItemRoleClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkItemRoleClient(cc grpc.ClientConnInterface) WorkItemRoleClient {
	return &workItemRoleClient{cc}
}

func (c *workItemRoleClient) QSpaceRoleList(ctx context.Context, in *SpaceRoleListQueryRequest, opts ...grpc.CallOption) (*SpaceRoleListQueryReply, error) {
	out := new(SpaceRoleListQueryReply)
	err := c.cc.Invoke(ctx, WorkItemRole_QSpaceRoleList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workItemRoleClient) SetSpaceWorkItemRoleRanking(ctx context.Context, in *SetSpaceWorkItemRoleRankingRequest, opts ...grpc.CallOption) (*SetSpaceWorkItemRoleRankingReply, error) {
	out := new(SetSpaceWorkItemRoleRankingReply)
	err := c.cc.Invoke(ctx, WorkItemRole_SetSpaceWorkItemRoleRanking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workItemRoleClient) SetSpaceWorkItemRoleName(ctx context.Context, in *SetSpaceWorkItemRoleNameRequest, opts ...grpc.CallOption) (*SetSpaceWorkItemRoleNameReply, error) {
	out := new(SetSpaceWorkItemRoleNameReply)
	err := c.cc.Invoke(ctx, WorkItemRole_SetSpaceWorkItemRoleName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workItemRoleClient) DelSpaceWorkItemRole(ctx context.Context, in *DelSpaceWorkItemRoleRequest, opts ...grpc.CallOption) (*DelSpaceWorkItemRoleReply, error) {
	out := new(DelSpaceWorkItemRoleReply)
	err := c.cc.Invoke(ctx, WorkItemRole_DelSpaceWorkItemRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workItemRoleClient) CreateSpaceWorkItemRole(ctx context.Context, in *CreateSpaceWorkItemRoleRequest, opts ...grpc.CallOption) (*CreateSpaceWorkItemRoleReply, error) {
	out := new(CreateSpaceWorkItemRoleReply)
	err := c.cc.Invoke(ctx, WorkItemRole_CreateSpaceWorkItemRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workItemRoleClient) GetWorkItemRelationCount(ctx context.Context, in *GetWorkItemRelationCountRequest, opts ...grpc.CallOption) (*GetWorkItemRelationCountReply, error) {
	out := new(GetWorkItemRelationCountReply)
	err := c.cc.Invoke(ctx, WorkItemRole_GetWorkItemRelationCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workItemRoleClient) GetTemplateRelationCount(ctx context.Context, in *GetTemplateRelationCountRequest, opts ...grpc.CallOption) (*GetTemplateRelationCountReply, error) {
	out := new(GetTemplateRelationCountReply)
	err := c.cc.Invoke(ctx, WorkItemRole_GetTemplateRelationCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkItemRoleServer is the server API for WorkItemRole service.
// All implementations must embed UnimplementedWorkItemRoleServer
// for forward compatibility
type WorkItemRoleServer interface {
	QSpaceRoleList(context.Context, *SpaceRoleListQueryRequest) (*SpaceRoleListQueryReply, error)
	SetSpaceWorkItemRoleRanking(context.Context, *SetSpaceWorkItemRoleRankingRequest) (*SetSpaceWorkItemRoleRankingReply, error)
	SetSpaceWorkItemRoleName(context.Context, *SetSpaceWorkItemRoleNameRequest) (*SetSpaceWorkItemRoleNameReply, error)
	DelSpaceWorkItemRole(context.Context, *DelSpaceWorkItemRoleRequest) (*DelSpaceWorkItemRoleReply, error)
	CreateSpaceWorkItemRole(context.Context, *CreateSpaceWorkItemRoleRequest) (*CreateSpaceWorkItemRoleReply, error)
	GetWorkItemRelationCount(context.Context, *GetWorkItemRelationCountRequest) (*GetWorkItemRelationCountReply, error)
	GetTemplateRelationCount(context.Context, *GetTemplateRelationCountRequest) (*GetTemplateRelationCountReply, error)
	mustEmbedUnimplementedWorkItemRoleServer()
}

// UnimplementedWorkItemRoleServer must be embedded to have forward compatible implementations.
type UnimplementedWorkItemRoleServer struct {
}

func (UnimplementedWorkItemRoleServer) QSpaceRoleList(context.Context, *SpaceRoleListQueryRequest) (*SpaceRoleListQueryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QSpaceRoleList not implemented")
}
func (UnimplementedWorkItemRoleServer) SetSpaceWorkItemRoleRanking(context.Context, *SetSpaceWorkItemRoleRankingRequest) (*SetSpaceWorkItemRoleRankingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSpaceWorkItemRoleRanking not implemented")
}
func (UnimplementedWorkItemRoleServer) SetSpaceWorkItemRoleName(context.Context, *SetSpaceWorkItemRoleNameRequest) (*SetSpaceWorkItemRoleNameReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSpaceWorkItemRoleName not implemented")
}
func (UnimplementedWorkItemRoleServer) DelSpaceWorkItemRole(context.Context, *DelSpaceWorkItemRoleRequest) (*DelSpaceWorkItemRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelSpaceWorkItemRole not implemented")
}
func (UnimplementedWorkItemRoleServer) CreateSpaceWorkItemRole(context.Context, *CreateSpaceWorkItemRoleRequest) (*CreateSpaceWorkItemRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSpaceWorkItemRole not implemented")
}
func (UnimplementedWorkItemRoleServer) GetWorkItemRelationCount(context.Context, *GetWorkItemRelationCountRequest) (*GetWorkItemRelationCountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkItemRelationCount not implemented")
}
func (UnimplementedWorkItemRoleServer) GetTemplateRelationCount(context.Context, *GetTemplateRelationCountRequest) (*GetTemplateRelationCountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplateRelationCount not implemented")
}
func (UnimplementedWorkItemRoleServer) mustEmbedUnimplementedWorkItemRoleServer() {}

// UnsafeWorkItemRoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkItemRoleServer will
// result in compilation errors.
type UnsafeWorkItemRoleServer interface {
	mustEmbedUnimplementedWorkItemRoleServer()
}

func RegisterWorkItemRoleServer(s grpc.ServiceRegistrar, srv WorkItemRoleServer) {
	s.RegisterService(&WorkItemRole_ServiceDesc, srv)
}

func _WorkItemRole_QSpaceRoleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpaceRoleListQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkItemRoleServer).QSpaceRoleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkItemRole_QSpaceRoleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkItemRoleServer).QSpaceRoleList(ctx, req.(*SpaceRoleListQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkItemRole_SetSpaceWorkItemRoleRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSpaceWorkItemRoleRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkItemRoleServer).SetSpaceWorkItemRoleRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkItemRole_SetSpaceWorkItemRoleRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkItemRoleServer).SetSpaceWorkItemRoleRanking(ctx, req.(*SetSpaceWorkItemRoleRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkItemRole_SetSpaceWorkItemRoleName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSpaceWorkItemRoleNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkItemRoleServer).SetSpaceWorkItemRoleName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkItemRole_SetSpaceWorkItemRoleName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkItemRoleServer).SetSpaceWorkItemRoleName(ctx, req.(*SetSpaceWorkItemRoleNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkItemRole_DelSpaceWorkItemRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelSpaceWorkItemRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkItemRoleServer).DelSpaceWorkItemRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkItemRole_DelSpaceWorkItemRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkItemRoleServer).DelSpaceWorkItemRole(ctx, req.(*DelSpaceWorkItemRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkItemRole_CreateSpaceWorkItemRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSpaceWorkItemRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkItemRoleServer).CreateSpaceWorkItemRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkItemRole_CreateSpaceWorkItemRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkItemRoleServer).CreateSpaceWorkItemRole(ctx, req.(*CreateSpaceWorkItemRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkItemRole_GetWorkItemRelationCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkItemRelationCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkItemRoleServer).GetWorkItemRelationCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkItemRole_GetWorkItemRelationCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkItemRoleServer).GetWorkItemRelationCount(ctx, req.(*GetWorkItemRelationCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkItemRole_GetTemplateRelationCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateRelationCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkItemRoleServer).GetTemplateRelationCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkItemRole_GetTemplateRelationCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkItemRoleServer).GetTemplateRelationCount(ctx, req.(*GetTemplateRelationCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkItemRole_ServiceDesc is the grpc.ServiceDesc for WorkItemRole service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkItemRole_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.work_item_role.v1.WorkItemRole",
	HandlerType: (*WorkItemRoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QSpaceRoleList",
			Handler:    _WorkItemRole_QSpaceRoleList_Handler,
		},
		{
			MethodName: "SetSpaceWorkItemRoleRanking",
			Handler:    _WorkItemRole_SetSpaceWorkItemRoleRanking_Handler,
		},
		{
			MethodName: "SetSpaceWorkItemRoleName",
			Handler:    _WorkItemRole_SetSpaceWorkItemRoleName_Handler,
		},
		{
			MethodName: "DelSpaceWorkItemRole",
			Handler:    _WorkItemRole_DelSpaceWorkItemRole_Handler,
		},
		{
			MethodName: "CreateSpaceWorkItemRole",
			Handler:    _WorkItemRole_CreateSpaceWorkItemRole_Handler,
		},
		{
			MethodName: "GetWorkItemRelationCount",
			Handler:    _WorkItemRole_GetWorkItemRelationCount_Handler,
		},
		{
			MethodName: "GetTemplateRelationCount",
			Handler:    _WorkItemRole_GetTemplateRelationCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "work_item_role/v1/work_item_role.proto",
}
